<?php

/**
 * Implements hook_menu().
 */
function aasa_content_menu() {

    $items['board-member-bios'] = array(
        'page callback' => 'aasa_content_board_member_bios_page',
        'page arguments' => array(),
        'access callback' => TRUE,
        'title' => '2016 Executive Committee Nomination Bios'
    );
    return $items;
}

/**
 * Implements hook_theme().
 */
function aasa_content_theme($existing, $type, $theme, $path) {
    return array('board_members_bios' => array(
            'template' => 'templates/board-members-bios',
            'variables' => array('bios' => NULL),
        ),
    );
}
 
function aasa_content_get_bios_by_category($tid){
	$query = new EntityFieldQuery();
	$query->entityCondition('entity_type', 'node')
		->entityCondition('bundle', 'bios')
		->propertyCondition('status', NODE_PUBLISHED)
		->fieldCondition('field_bio_category', 'tid', $tid)
		->propertyOrderBy('title','Asc');
	$result = $query->execute();
	$bios = array();
	if (isset($result['node'])) {
	  $news_items_nids = array_keys($result['node']);
	  $bios = entity_load('node', $news_items_nids);
	}	
	return $bios;
}

function aasa_content_board_member_bios_page(){
	$categories =  taxonomy_get_tree($vid = 2);
	$items = array();
	foreach ($categories as $key => $category) {
		$tid = $category->tid;
		$item = array();
		$item['category_label'] =  $category->name;
		$item['category_tid'] =  $category->tid;
		$item['category_bios'] =  array();
		$item['category_bios'] =  aasa_content_get_bios_by_category($tid);
		$items[] = $item;
	}
	$htmt_output = theme('board_members_bios', array('bios' => $items));
	drupal_add_js(drupal_get_path('module', 'aasa_content') . '/js/board-members-bios.js');
	drupal_add_css(drupal_get_path('module', 'aasa_content') . '/css/board-members-bios.css');
	return array('#markup' => $htmt_output);
}