<?php

/**
 * Implements hook_menu().
 */
function aasa_content_menu() {

    $items['board-member-bios'] = array(
        'page callback' => 'aasa_content_board_member_bios_page',
        'page arguments' => array(),
        'access callback' => TRUE,
        'title' => 'Board Member Bios'
    );
    return $items;
}
 
function aasa_content_board_member_bios_page(){
	$categories =  taxonomy_get_tree($vid = 2);
	$items = array();
	foreach ($categories as $key => $category) {
		

	}
	return "";
}