<?php
mail($submission->data[EVENT_EMAIL_FIELD_ID][0], SITE_NAME.' Event Payment Instructions','Thank you for registering for the '.SITE_NAME.' '.$node->title.'. '
  .'We have received notification you will pay registration in the form of a check.'. "\r\n \r\n"
  .'Please make check payable to: '.SITE_NAME.' and send to:'. "\r\n \r\n"
  .'Benson Won, MPH'."\r\n"
  .'Chief Administrative Officer'. "\r\n"
  .'Department of Surgery'. "\r\n"
  .'UC Davis School of Medicine'. "\r\n"
  .'UC Davis Health System'."\r\n"
  .'916-734-7886'."\r\n"
  .'http://surgery.ucdmc.ucdavis.edu'."\r\n \r\n"
  .'Registration Receipt'. "\r\n"
  .'Date: '.date("n/j/y",$submission->submitted)."\r\n"
  .'Payment Type: Check'. "\r\n \r\n"
  .$node->title. "\r\n"
  .'Registration Fee $'.$reg_fee."\r\n"
  .'Guest $'.$vent_guest."\r\n"
  .'------------------------------------------------'. "\r\n"
  .'Event Registration'."\r\n"
  .'$'.$reg_fee."\r\n"
  .'Guest'."\r\n"
  .'$'.$vent_guest."\r\n"
  .'------------------------------------------------'. "\r\n"
  .'Grand Total'."\r\n"
  .'$'.$event_price. "\r\n \r\n"
  .'Name: '.$submission->data[1][0]." ".$submission->data[2][0]. "\r\n"
  .'Organization: '.$submission->data[5][0]. "\r\n"
  .'Email: '.$submission->data[EVENT_EMAIL_FIELD_ID][0]. "\r\n"
  .'Address Line 1: '.$submission->data[6][0]. "\r\n"
  .'Address Line 2: '.$submission->data[7][0]. "\r\n"
  .'City: '.$submission->data[8][0]. "\r\n"
  .'State/Province: '.$submission->data[9][0]. "\r\n"
  .'Zip/Postal Code: '.$submission->data[10][0]. "\r\n \r\n"
  .'Thank you,'. "\r\n \r\n"
  .SITE_NAME, HEADERS);
